/**
 * Generate SQL seed for the assessment template library from the versioned
 * framework JSON in @cpf/assessment-framework.
 *
 * Output: packages/db/seed/generated/seed.sql (idempotent; safe to re-run).
 * Usage:  npm run seed:generate
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "..", "assessment-framework", "data");
const outDir = join(here, "..", "seed", "generated");
mkdirSync(outDir, { recursive: true });

const templatesDir = join(dataDir, "templates");
const files = readdirSync(templatesDir).filter((f) => f.endsWith(".json")).sort();

const sqlEscape = (s) => s.replace(/'/g, "''");
const lines = [
  "-- Generated by packages/db/scripts/generate-seed.mjs — do not edit by hand.",
  "-- Idempotent seed of the versioned assessment template library.",
  "BEGIN;",
];

for (const file of files) {
  const raw = readFileSync(join(templatesDir, file), "utf-8");
  const tpl = JSON.parse(raw);
  const sha = createHash("sha256").update(raw).digest("hex");
  const def = sqlEscape(JSON.stringify(tpl));
  lines.push(
    `INSERT INTO assessment_templates (code, role_family, status)
VALUES ('${tpl.code}', '${tpl.roleFamily}', 'published')
ON CONFLICT (code) DO NOTHING;`,
    `INSERT INTO assessment_template_versions (template_id, framework_version, definition, definition_sha256, published_at)
SELECT t.id, '${tpl.frameworkVersion}', '${def}'::jsonb, '${sha}', now()
FROM assessment_templates t
WHERE t.code = '${tpl.code}'
ON CONFLICT (template_id, framework_version) DO NOTHING;`,
  );
}

lines.push("COMMIT;", "");
writeFileSync(join(outDir, "seed.sql"), lines.join("\n\n"));
console.log(`Wrote seed for ${files.length} templates to seed/generated/seed.sql`);
